- name: Configure server
  hosts: henry_server
  sudo: true
  vars_files:
    - vars.yml
    - secrets.yml
  handlers:
    - name: reload systemd
      command: systemctl daemon-reload
    - name: restart hubot
      service: name=hubot state=restarted
  tasks:
    - name: add ansible apt repository
      apt_repository: repo="ppa:ansible/ansible"

    - name: install packages
      apt: name={{ item }} update_cache=true
      with_items:
        - git
        - nodejs-legacy
        - npm
        - software-properties-common
        - ansible

    - name: clone source
      git: repo=https://github.com/teamgantt/henry.git
           dest={{ hubot_directory }}
           update=false

    - name: add hubot service
      template: src=files/hubot.service.j2 dest=/etc/systemd/system/hubot.service
      notify:
        - reload systemd
        - restart hubot
